### PR TITLE
fix: deleted contributing guide doc

### PR DESCRIPTION
**Pull request by oyenuga17**
**This pull request makes the following changes:**
* Fixes issue #6

**Checklist:**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me
- [x] I certify that I ran my checklist.

Ping @Ifycode/git-github-training-resource

### CODE REVIEW

**Comment by oyenuga17** [comment]
@Ifycode  please review

**Review by Ifycode — CHANGES_REQUESTED** [review]
Please remove the ds store file that got added along when you were deleting @oyenuga17

**Comment by oyenuga17** [comment]
@Ifycode  please review

**Comment by oyenuga17** [comment]
> Please remove the ds store file that got added along when you were deleting @oyenuga17

done

**Review by Ifycode — CHANGES_REQUESTED** [review]
See the screenshots below that confirms you have not removed the ds store file that got added while making your changes to the course repo. Check your fork again and remove it @oyenuga17 

#### From your fork
send1

#### Files changes from this PR
send2

**Comment by oyenuga17** [comment]
@Ifycode done

**Comment by oyenuga17** [comment]
@Ifycode  please review

**Review by Ifycode — APPROVED** [review]

**Pull request merged**
